### ISSUE TITLE
Php Api sample code is crashing

### ISSUE THREAD

**Issue by davidbiii** [synapsepayments/synapse_pay-php#1]
The php api code crashes.
After the successful call to the server, the responses is process and the system crashes.
on the line $this->klass

of refreshFrom.

![screen shot 2015-05-15 at 10 02 48 am](https://cloud.githubusercontent.com/assets/12461637/7654525/c728d324-faeb-11e4-93bd-83e53b422be6.png)

**Comment by joncalhoun** [comment]
This should be working now. From what I can tell, the PHP lib is working reasonably well now, but truthfully we need to get tests pushed to it pronto and are working on those now.
